### ISSUE TITLE
Is cachepy thread safe?

### ISSUE THREAD

**Issue by dragz** [scidam/cachepy#2]
Hi, I'm considering cachepy as the solution for a small web-app based on Bottle for the server side. The Bottle server runs behind Apache for scalability and performance. As Apache will start serveral Bottle processes the question is: Will cachepy keep a consistent file cache that can be shared between all Bottle processes?

Best regards,
Roy.

**Comment by scidam** [comment]
Hi, Roy!
Cachepy relies on Python's shelve module when storing cached data.  Shelve isn't a thread safe app, so, cachepy isn't  thread safe app as well. When Redis-based caching will be implemented, it will be thread-safe.  I will try to implement this feature until the end of the month.

**Comment by dragz** [comment]
OK, thanks for the quick answer. I'll have to consider my options. Per-thread memory caching will suffice for now.

Best regards,
Roy.
